// Thanks to https://gist.github.com/bantya/9a619ab7b8f262e83fda
var countriesFlags = [
    { "name": "Afghanistan", "mini": "http://flags.fmcdn.net/data/flags/mini/af.png", "normal": "http://flags.fmcdn.net/data/flags/big/af.png" },
    { "name": "Albania", "mini": "http://flags.fmcdn.net/data/flags/mini/al.png", "normal": "http://flags.fmcdn.net/data/flags/big/al.png" },
    { "name": "Algeria", "mini": "http://flags.fmcdn.net/data/flags/mini/dz.png", "normal": "http://flags.fmcdn.net/data/flags/big/dz.png" },
    { "name": "Andorra", "mini": "http://flags.fmcdn.net/data/flags/mini/ad.png", "normal": "http://flags.fmcdn.net/data/flags/big/ad.png" },
    { "name": "Angola", "mini": "http://flags.fmcdn.net/data/flags/mini/ao.png", "normal": "http://flags.fmcdn.net/data/flags/big/ao.png" },
    { "name": "Antigua", "alias": "Antigua and Barbuda", "mini": "http://flags.fmcdn.net/data/flags/mini/ag.png", "normal": "http://flags.fmcdn.net/data/flags/big/ag.png" },
    { "name": "Argentina", "mini": "http://flags.fmcdn.net/data/flags/mini/ar.png", "normal": "http://flags.fmcdn.net/data/flags/big/ar.png" },
    { "name": "Armenia", "mini": "http://flags.fmcdn.net/data/flags/mini/am.png", "normal": "http://flags.fmcdn.net/data/flags/big/am.png" },
    { "name": "Australia", "mini": "http://flags.fmcdn.net/data/flags/mini/au.png", "normal": "http://flags.fmcdn.net/data/flags/big/au.png" },
    { "name": "Austria", "mini": "http://flags.fmcdn.net/data/flags/mini/at.png", "normal": "http://flags.fmcdn.net/data/flags/big/at.png" },
    { "name": "Azerbaijan", "mini": "http://flags.fmcdn.net/data/flags/mini/az.png", "normal": "http://flags.fmcdn.net/data/flags/big/az.png" },
    { "name": "Bahamas", "mini": "http://flags.fmcdn.net/data/flags/mini/bs.png", "normal": "http://flags.fmcdn.net/data/flags/big/bs.png" },
    { "name": "Bahrain", "mini": "http://flags.fmcdn.net/data/flags/mini/bh.png", "normal": "http://flags.fmcdn.net/data/flags/big/bh.png" },
    { "name": "Bangladesh", "mini": "http://flags.fmcdn.net/data/flags/mini/bd.png", "normal": "http://flags.fmcdn.net/data/flags/big/bd.png" },
    { "name": "Barbados", "mini": "http://flags.fmcdn.net/data/flags/mini/bb.png", "normal": "http://flags.fmcdn.net/data/flags/big/bb.png" },
    { "name": "Belarus", "mini": "http://flags.fmcdn.net/data/flags/mini/by.png", "normal": "http://flags.fmcdn.net/data/flags/big/by.png" },
    { "name": "Belgium", "mini": "http://flags.fmcdn.net/data/flags/mini/be.png", "normal": "http://flags.fmcdn.net/data/flags/big/be.png" },
    { "name": "Belize", "mini": "http://flags.fmcdn.net/data/flags/mini/bz.png", "normal": "http://flags.fmcdn.net/data/flags/big/bz.png" },
    { "name": "Benin", "mini": "http://flags.fmcdn.net/data/flags/mini/bj.png", "normal": "http://flags.fmcdn.net/data/flags/big/bj.png" },
    { "name": "Bhutan", "mini": "http://flags.fmcdn.net/data/flags/mini/bt.png", "normal": "http://flags.fmcdn.net/data/flags/big/bt.png" },
    { "name": "Bolivia", "mini": "http://flags.fmcdn.net/data/flags/mini/bo.png", "normal": "http://flags.fmcdn.net/data/flags/big/bo.png" },
    { "name": "Bosnia", "alias": "Bosnia and Herzegovina", "mini": "http://flags.fmcdn.net/data/flags/mini/ba.png", "normal": "http://flags.fmcdn.net/data/flags/big/ba.png" },
    { "name": "Botswana", "mini": "http://flags.fmcdn.net/data/flags/mini/bw.png", "normal": "http://flags.fmcdn.net/data/flags/big/bw.png" },
    { "name": "Brazil", "mini": "http://flags.fmcdn.net/data/flags/mini/br.png", "normal": "http://flags.fmcdn.net/data/flags/big/br.png" },
    { "name": "Brunei", "mini": "http://flags.fmcdn.net/data/flags/mini/bn.png", "normal": "http://flags.fmcdn.net/data/flags/big/bn.png" },
    { "name": "Bulgaria", "mini": "http://flags.fmcdn.net/data/flags/mini/bg.png", "normal": "http://flags.fmcdn.net/data/flags/big/bg.png" },
    { "name": "Burkina", "alias": "Burkina Faso", "mini": "http://flags.fmcdn.net/data/flags/mini/bf.png", "normal": "http://flags.fmcdn.net/data/flags/big/bf.png" },
    { "name": "Burundi", "mini": "http://flags.fmcdn.net/data/flags/mini/bi.png", "normal": "http://flags.fmcdn.net/data/flags/big/bi.png" },
    { "name": "Cambodia", "mini": "http://flags.fmcdn.net/data/flags/mini/kh.png", "normal": "http://flags.fmcdn.net/data/flags/big/kh.png" },
    { "name": "Cameroon", "mini": "http://flags.fmcdn.net/data/flags/mini/cm.png", "normal": "http://flags.fmcdn.net/data/flags/big/cm.png" },
    { "name": "Canada", "mini": "http://flags.fmcdn.net/data/flags/mini/ca.png", "normal": "http://flags.fmcdn.net/data/flags/big/ca.png" },
    { "name": "Verde", "alias": "Cape Verde", "mini": "http://flags.fmcdn.net/data/flags/mini/cv.png", "normal": "http://flags.fmcdn.net/data/flags/big/cv.png" },
    { "name": "CAR", "alias": "Central African Republic", "mini": "http://flags.fmcdn.net/data/flags/mini/cf.png", "normal": "http://flags.fmcdn.net/data/flags/big/cf.png" },
    { "name": "Chad", "mini": "http://flags.fmcdn.net/data/flags/mini/td.png", "normal": "http://flags.fmcdn.net/data/flags/big/td.png" },
    { "name": "Chile", "mini": "http://flags.fmcdn.net/data/flags/mini/cl.png", "normal": "http://flags.fmcdn.net/data/flags/big/cl.png" },
    { "name": "Colombia", "mini": "http://flags.fmcdn.net/data/flags/mini/co.png", "normal": "http://flags.fmcdn.net/data/flags/big/co.png" },
    { "name": "Comoros", "mini": "http://flags.fmcdn.net/data/flags/mini/km.png", "normal": "http://flags.fmcdn.net/data/flags/big/km.png" },
    { "name": "Cook", "alias": "Cook Islands", "mini": "http://flags.fmcdn.net/data/flags/mini/ck.png", "normal": "http://flags.fmcdn.net/data/flags/big/ck.png" },
    { "name": "CostaRica", "alias": "Costa Rica", "mini": "http://flags.fmcdn.net/data/flags/mini/cr.png", "normal": "http://flags.fmcdn.net/data/flags/big/cr.png" },
    { "name": "Ivoire", "alias": "Cote d'Ivoire", "mini": "http://flags.fmcdn.net/data/flags/mini/ci.png", "normal": "http://flags.fmcdn.net/data/flags/big/ci.png" },
    { "name": "Croatia", "mini": "http://flags.fmcdn.net/data/flags/mini/hr.png", "normal": "http://flags.fmcdn.net/data/flags/big/hr.png" },
    { "name": "Cuba", "mini": "http://flags.fmcdn.net/data/flags/mini/cu.png", "normal": "http://flags.fmcdn.net/data/flags/big/cu.png" },
    { "name": "Cyprus", "mini": "http://flags.fmcdn.net/data/flags/mini/cy.png", "normal": "http://flags.fmcdn.net/data/flags/big/cy.png" },
    { "name": "Czech", "alias": "Czech Republic", "mini": "http://flags.fmcdn.net/data/flags/mini/cz.png", "normal": "http://flags.fmcdn.net/data/flags/big/cz.png" },
    { "name": "DRC", "alias": "Democratic Republic of the Congo", "mini": "http://flags.fmcdn.net/data/flags/mini/cd.png", "normal": "http://flags.fmcdn.net/data/flags/big/cd.png" },
    { "name": "Denmark", "mini": "http://flags.fmcdn.net/data/flags/mini/dk.png", "normal": "http://flags.fmcdn.net/data/flags/big/dk.png" },
    { "name": "Djibouti", "mini": "http://flags.fmcdn.net/data/flags/mini/dj.png", "normal": "http://flags.fmcdn.net/data/flags/big/dj.png" },
    { "name": "Dominica", "mini": "http://flags.fmcdn.net/data/flags/mini/dm.png", "normal": "http://flags.fmcdn.net/data/flags/big/dm.png" },
    { "name": "DR", "alias": "Dominican Republic", "mini": "http://flags.fmcdn.net/data/flags/mini/do.png", "normal": "http://flags.fmcdn.net/data/flags/big/do.png" },
    { "name": "Timor", "alias": "East Timor", "mini": "http://flags.fmcdn.net/data/flags/mini/tl.png", "normal": "http://flags.fmcdn.net/data/flags/big/tl.png" },
    { "name": "Ecuador", "mini": "http://flags.fmcdn.net/data/flags/mini/ec.png", "normal": "http://flags.fmcdn.net/data/flags/big/ec.png" },
    { "name": "Egypt", "mini": "http://flags.fmcdn.net/data/flags/mini/eg.png", "normal": "http://flags.fmcdn.net/data/flags/big/eg.png" },
    { "name": "Salvador", "alias": "El Salvador", "mini": "http://flags.fmcdn.net/data/flags/mini/sv.png", "normal": "http://flags.fmcdn.net/data/flags/big/sv.png" },
    { "name": "EGuinea", "alias": "Equatorial Guinea", "mini": "http://flags.fmcdn.net/data/flags/mini/gq.png", "normal": "http://flags.fmcdn.net/data/flags/big/gq.png" },
    { "name": "Eritrea", "mini": "http://flags.fmcdn.net/data/flags/mini/er.png", "normal": "http://flags.fmcdn.net/data/flags/big/er.png" },
    { "name": "Estonia", "mini": "http://flags.fmcdn.net/data/flags/mini/ee.png", "normal": "http://flags.fmcdn.net/data/flags/big/ee.png" },
    { "name": "Ethiopia", "mini": "http://flags.fmcdn.net/data/flags/mini/et.png", "normal": "http://flags.fmcdn.net/data/flags/big/et.png" },
    { "name": "Fiji", "mini": "http://flags.fmcdn.net/data/flags/mini/fj.png", "normal": "http://flags.fmcdn.net/data/flags/big/fj.png" },
    { "name": "Finland", "mini": "http://flags.fmcdn.net/data/flags/mini/fi.png", "normal": "http://flags.fmcdn.net/data/flags/big/fi.png" },
    { "name": "France", "mini": "http://flags.fmcdn.net/data/flags/mini/fr.png", "normal": "http://flags.fmcdn.net/data/flags/big/fr.png" },
    { "name": "Gabon", "mini": "http://flags.fmcdn.net/data/flags/mini/ga.png", "normal": "http://flags.fmcdn.net/data/flags/big/ga.png" },
    { "name": "Gambia", "mini": "http://flags.fmcdn.net/data/flags/mini/gm.png", "normal": "http://flags.fmcdn.net/data/flags/big/gm.png" },
    { "name": "Georgia", "mini": "http://flags.fmcdn.net/data/flags/mini/ge.png", "normal": "http://flags.fmcdn.net/data/flags/big/ge.png" },
    { "name": "Germany", "mini": "http://flags.fmcdn.net/data/flags/mini/de.png", "normal": "http://flags.fmcdn.net/data/flags/big/de.png" },
    { "name": "Ghana", "mini": "http://flags.fmcdn.net/data/flags/mini/gh.png", "normal": "http://flags.fmcdn.net/data/flags/big/gh.png" },
    { "name": "Greece", "mini": "http://flags.fmcdn.net/data/flags/mini/gr.png", "normal": "http://flags.fmcdn.net/data/flags/big/gr.png" },
    { "name": "Grenada", "mini": "http://flags.fmcdn.net/data/flags/mini/gd.png", "normal": "http://flags.fmcdn.net/data/flags/big/gd.png" },
    { "name": "Guatemala", "mini": "http://flags.fmcdn.net/data/flags/mini/gt.png", "normal": "http://flags.fmcdn.net/data/flags/big/gt.png" },
    { "name": "Guinea", "mini": "http://flags.fmcdn.net/data/flags/mini/gn.png", "normal": "http://flags.fmcdn.net/data/flags/big/gn.png" },
    { "name": "GuineaB", "alias": "Guinea-Bissau", "mini": "http://flags.fmcdn.net/data/flags/mini/gw.png", "normal": "http://flags.fmcdn.net/data/flags/big/gw.png" },
    { "name": "Guyana", "mini": "http://flags.fmcdn.net/data/flags/mini/gy.png", "normal": "http://flags.fmcdn.net/data/flags/big/gy.png" },
    { "name": "Haiti", "mini": "http://flags.fmcdn.net/data/flags/mini/ht.png", "normal": "http://flags.fmcdn.net/data/flags/big/ht.png" },
    { "name": "Honduras", "mini": "http://flags.fmcdn.net/data/flags/mini/hn.png", "normal": "http://flags.fmcdn.net/data/flags/big/hn.png" },
    { "name": "Hungary", "mini": "http://flags.fmcdn.net/data/flags/mini/hu.png", "normal": "http://flags.fmcdn.net/data/flags/big/hu.png" },
    { "name": "Iceland", "mini": "http://flags.fmcdn.net/data/flags/mini/is.png", "normal": "http://flags.fmcdn.net/data/flags/big/is.png" },
    { "name": "India", "mini": "http://flags.fmcdn.net/data/flags/mini/in.png", "normal": "http://flags.fmcdn.net/data/flags/big/in.png" },
    { "name": "Indonesia", "mini": "http://flags.fmcdn.net/data/flags/mini/id.png", "normal": "http://flags.fmcdn.net/data/flags/big/id.png" },
    { "name": "Iran", "mini": "http://flags.fmcdn.net/data/flags/mini/ir.png", "normal": "http://flags.fmcdn.net/data/flags/big/ir.png" },
    { "name": "Iraq", "mini": "http://flags.fmcdn.net/data/flags/mini/iq.png", "normal": "http://flags.fmcdn.net/data/flags/big/iq.png" },
    { "name": "Ireland", "mini": "http://flags.fmcdn.net/data/flags/mini/ie.png", "normal": "http://flags.fmcdn.net/data/flags/big/ie.png" },
    { "name": "Israel", "mini": "http://flags.fmcdn.net/data/flags/mini/il.png", "normal": "http://flags.fmcdn.net/data/flags/big/il.png" },
    { "name": "Italy", "mini": "http://flags.fmcdn.net/data/flags/mini/it.png", "normal": "http://flags.fmcdn.net/data/flags/big/it.png" },
    { "name": "Jamaica", "mini": "http://flags.fmcdn.net/data/flags/mini/jm.png", "normal": "http://flags.fmcdn.net/data/flags/big/jm.png" },
    { "name": "Japan", "mini": "http://flags.fmcdn.net/data/flags/mini/jp.png", "normal": "http://flags.fmcdn.net/data/flags/big/jp.png" },
    { "name": "Jordan", "mini": "http://flags.fmcdn.net/data/flags/mini/jo.png", "normal": "http://flags.fmcdn.net/data/flags/big/jo.png" },
    { "name": "Kazakhstan", "mini": "http://flags.fmcdn.net/data/flags/mini/kz.png", "normal": "http://flags.fmcdn.net/data/flags/big/kz.png" },
    { "name": "Kenya", "mini": "http://flags.fmcdn.net/data/flags/mini/ke.png", "normal": "http://flags.fmcdn.net/data/flags/big/ke.png" },
    { "name": "Kiribati", "mini": "http://flags.fmcdn.net/data/flags/mini/ki.png", "normal": "http://flags.fmcdn.net/data/flags/big/ki.png" },
    { "name": "Kosovo", "mini": "http://flags.fmcdn.net/data/flags/mini/ks.png", "normal": "http://flags.fmcdn.net/data/flags/big/ks.png" },
    { "name": "Kuwait", "mini": "http://flags.fmcdn.net/data/flags/mini/kw.png", "normal": "http://flags.fmcdn.net/data/flags/big/kw.png" },
    { "name": "Kyrgyzstan", "mini": "http://flags.fmcdn.net/data/flags/mini/kg.png", "normal": "http://flags.fmcdn.net/data/flags/big/kg.png" },
    { "name": "Laos", "mini": "http://flags.fmcdn.net/data/flags/mini/la.png", "normal": "http://flags.fmcdn.net/data/flags/big/la.png" },
    { "name": "Latvia", "mini": "http://flags.fmcdn.net/data/flags/mini/lv.png", "normal": "http://flags.fmcdn.net/data/flags/big/lv.png" },
    { "name": "Lebanon", "mini": "http://flags.fmcdn.net/data/flags/mini/lb.png", "normal": "http://flags.fmcdn.net/data/flags/big/lb.png" },
    { "name": "Lesotho", "mini": "http://flags.fmcdn.net/data/flags/mini/ls.png", "normal": "http://flags.fmcdn.net/data/flags/big/ls.png" },
    { "name": "Liberia", "mini": "http://flags.fmcdn.net/data/flags/mini/lr.png", "normal": "http://flags.fmcdn.net/data/flags/big/lr.png" },
    { "name": "Libya", "mini": "http://flags.fmcdn.net/data/flags/mini/ly.png", "normal": "http://flags.fmcdn.net/data/flags/big/ly.png" },
    { "name": "Liechtenstein", "mini": "http://flags.fmcdn.net/data/flags/mini/li.png", "normal": "http://flags.fmcdn.net/data/flags/big/li.png" },
    { "name": "Lithuania", "mini": "http://flags.fmcdn.net/data/flags/mini/lt.png", "normal": "http://flags.fmcdn.net/data/flags/big/lt.png" },
    { "name": "Luxembourg", "mini": "http://flags.fmcdn.net/data/flags/mini/lu.png", "normal": "http://flags.fmcdn.net/data/flags/big/lu.png" },
    { "name": "Macedonia", "mini": "http://flags.fmcdn.net/data/flags/mini/mk.png", "normal": "http://flags.fmcdn.net/data/flags/big/mk.png" },
    { "name": "Madagascar", "mini": "http://flags.fmcdn.net/data/flags/mini/mg.png", "normal": "http://flags.fmcdn.net/data/flags/big/mg.png" },
    { "name": "Malawi", "mini": "http://flags.fmcdn.net/data/flags/mini/mw.png", "normal": "http://flags.fmcdn.net/data/flags/big/mw.png" },
    { "name": "Malaysia", "mini": "http://flags.fmcdn.net/data/flags/mini/my.png", "normal": "http://flags.fmcdn.net/data/flags/big/my.png" },
    { "name": "Maldives", "mini": "http://flags.fmcdn.net/data/flags/mini/mv.png", "normal": "http://flags.fmcdn.net/data/flags/big/mv.png" },
    { "name": "Mali", "mini": "http://flags.fmcdn.net/data/flags/mini/ml.png", "normal": "http://flags.fmcdn.net/data/flags/big/ml.png" },
    { "name": "Malta", "mini": "http://flags.fmcdn.net/data/flags/mini/mt.png", "normal": "http://flags.fmcdn.net/data/flags/big/mt.png" },
    { "name": "Marshall", "alias": "Marshall Islands", "mini": "http://flags.fmcdn.net/data/flags/mini/mh.png", "normal": "http://flags.fmcdn.net/data/flags/big/mh.png" },
    { "name": "Mauritania", "mini": "http://flags.fmcdn.net/data/flags/mini/mr.png", "normal": "http://flags.fmcdn.net/data/flags/big/mr.png" },
    { "name": "Mauritius", "mini": "http://flags.fmcdn.net/data/flags/mini/mu.png", "normal": "http://flags.fmcdn.net/data/flags/big/mu.png" },
    { "name": "Mexico", "mini": "http://flags.fmcdn.net/data/flags/mini/mx.png", "normal": "http://flags.fmcdn.net/data/flags/big/mx.png" },
    { "name": "Micronesia", "mini": "http://flags.fmcdn.net/data/flags/mini/fm.png", "normal": "http://flags.fmcdn.net/data/flags/big/fm.png" },
    { "name": "Moldova", "mini": "http://flags.fmcdn.net/data/flags/mini/md.png", "normal": "http://flags.fmcdn.net/data/flags/big/md.png" },
    { "name": "Monaco", "mini": "http://flags.fmcdn.net/data/flags/mini/mc.png", "normal": "http://flags.fmcdn.net/data/flags/big/mc.png" },
    { "name": "Mongolia", "mini": "http://flags.fmcdn.net/data/flags/mini/mn.png", "normal": "http://flags.fmcdn.net/data/flags/big/mn.png" },
    { "name": "Montenegro", "mini": "http://flags.fmcdn.net/data/flags/mini/me.png", "normal": "http://flags.fmcdn.net/data/flags/big/me.png" },
    { "name": "Morocco", "mini": "http://flags.fmcdn.net/data/flags/mini/ma.png", "normal": "http://flags.fmcdn.net/data/flags/big/ma.png" },
    { "name": "Mozambique", "mini": "http://flags.fmcdn.net/data/flags/mini/mz.png", "normal": "http://flags.fmcdn.net/data/flags/big/mz.png" },
    { "name": "Myanmar", "mini": "http://flags.fmcdn.net/data/flags/mini/mm.png", "normal": "http://flags.fmcdn.net/data/flags/big/mm.png" },
    { "name": "Namibia", "mini": "http://flags.fmcdn.net/data/flags/mini/na.png", "normal": "http://flags.fmcdn.net/data/flags/big/na.png" },
    { "name": "Nauru", "mini": "http://flags.fmcdn.net/data/flags/mini/nr.png", "normal": "http://flags.fmcdn.net/data/flags/big/nr.png" },
    { "name": "Nepal", "mini": "http://flags.fmcdn.net/data/flags/mini/np.png", "normal": "http://flags.fmcdn.net/data/flags/big/np.png" },
    { "name": "Netherlands", "mini": "http://flags.fmcdn.net/data/flags/mini/nl.png", "normal": "http://flags.fmcdn.net/data/flags/big/nl.png" },
    { "name": "NZ", "alias": "New Zealand", "mini": "http://flags.fmcdn.net/data/flags/mini/nz.png", "normal": "http://flags.fmcdn.net/data/flags/big/nz.png" },
    { "name": "Nicaragua", "mini": "http://flags.fmcdn.net/data/flags/mini/ni.png", "normal": "http://flags.fmcdn.net/data/flags/big/ni.png" },
    { "name": "Niger", "mini": "http://flags.fmcdn.net/data/flags/mini/ne.png", "normal": "http://flags.fmcdn.net/data/flags/big/ne.png" },
    { "name": "Nigeria", "mini": "http://flags.fmcdn.net/data/flags/mini/ng.png", "normal": "http://flags.fmcdn.net/data/flags/big/ng.png" },
    { "name": "Niue", "mini": "http://flags.fmcdn.net/data/flags/mini/nu.png", "normal": "http://flags.fmcdn.net/data/flags/big/nu.png" },
    { "name": "NKorea", "alias": "DPRK", "mini": "http://flags.fmcdn.net/data/flags/mini/kp.png", "normal": "http://flags.fmcdn.net/data/flags/big/kp.png" },
    { "name": "Norway", "mini": "http://flags.fmcdn.net/data/flags/mini/no.png", "normal": "http://flags.fmcdn.net/data/flags/big/no.png" },
    { "name": "Oman", "mini": "http://flags.fmcdn.net/data/flags/mini/om.png", "normal": "http://flags.fmcdn.net/data/flags/big/om.png" },
    { "name": "Pakistan", "mini": "http://flags.fmcdn.net/data/flags/mini/pk.png", "normal": "http://flags.fmcdn.net/data/flags/big/pk.png" },
    { "name": "Palestine", "mini": "http://flags.fmcdn.net/data/flags/mini/ps.png", "normal": "http://flags.fmcdn.net/data/flags/big/ps.png" },
    { "name": "Palau", "mini": "http://flags.fmcdn.net/data/flags/mini/pw.png", "normal": "http://flags.fmcdn.net/data/flags/big/pw.png" },
    { "name": "Panama", "mini": "http://flags.fmcdn.net/data/flags/mini/pa.png", "normal": "http://flags.fmcdn.net/data/flags/big/pa.png" },
    { "name": "PGuinea", "alias": "Papua new Guinea", "mini": "http://flags.fmcdn.net/data/flags/mini/pg.png", "normal": "http://flags.fmcdn.net/data/flags/big/pg.png" },
    { "name": "Paraguay", "mini": "http://flags.fmcdn.net/data/flags/mini/py.png", "normal": "http://flags.fmcdn.net/data/flags/big/py.png" },
    { "name": "China", "alias": "The People's Republic of China", "mini": "http://flags.fmcdn.net/data/flags/mini/cn.png", "normal": "http://flags.fmcdn.net/data/flags/big/cn.png" },
    { "name": "Peru", "mini": "http://flags.fmcdn.net/data/flags/mini/pe.png", "normal": "http://flags.fmcdn.net/data/flags/big/pe.png" },
    { "name": "Philippines", "mini": "http://flags.fmcdn.net/data/flags/mini/ph.png", "normal": "http://flags.fmcdn.net/data/flags/big/ph.png" },
    { "name": "Poland", "mini": "http://flags.fmcdn.net/data/flags/mini/pl.png", "normal": "http://flags.fmcdn.net/data/flags/big/pl.png" },
    { "name": "Portugal", "mini": "http://flags.fmcdn.net/data/flags/mini/pt.png", "normal": "http://flags.fmcdn.net/data/flags/big/pt.png" },
    { "name": "Qatar", "mini": "http://flags.fmcdn.net/data/flags/mini/qa.png", "normal": "http://flags.fmcdn.net/data/flags/big/qa.png" },
    { "name": "Taiwan", "mini": "http://flags.fmcdn.net/data/flags/mini/tw.png", "normal": "http://flags.fmcdn.net/data/flags/big/tw.png" },
    { "name": "RC", "alias": "Republic of Congo", "mini": "http://flags.fmcdn.net/data/flags/mini/cg.png", "normal": "http://flags.fmcdn.net/data/flags/big/cg.png" },
    { "name": "Romania", "mini": "http://flags.fmcdn.net/data/flags/mini/ro.png", "normal": "http://flags.fmcdn.net/data/flags/big/ro.png" },
    { "name": "Russia", "mini": "http://flags.fmcdn.net/data/flags/mini/ru.png", "normal": "http://flags.fmcdn.net/data/flags/big/ru.png" },
    { "name": "Rwanda", "mini": "http://flags.fmcdn.net/data/flags/mini/rw.png", "normal": "http://flags.fmcdn.net/data/flags/big/rw.png" },
    { "name": "Scotland", "mini": "http://flags.fmcdn.net/data/flags/mini/gb-sct.png", "normal": "http://flags.fmcdn.net/data/flags/big/gb-sct.png" },
    { "name": "SKN", "alias": "Saint Kitts and Nevis", "mini": "http://flags.fmcdn.net/data/flags/mini/kn.png", "normal": "http://flags.fmcdn.net/data/flags/big/kn.png" },
    { "name": "SL", "alias": "Saint Lucia", "mini": "http://flags.fmcdn.net/data/flags/mini/lc.png", "normal": "http://flags.fmcdn.net/data/flags/big/lc.png" },
    { "name": "SVG", "alias": "Saint Vincent and the Grenadines", "mini": "http://flags.fmcdn.net/data/flags/mini/vc.png", "normal": "http://flags.fmcdn.net/data/flags/big/vc.png" },
    { "name": "Samoa", "mini": "http://flags.fmcdn.net/data/flags/mini/ws.png", "normal": "http://flags.fmcdn.net/data/flags/big/ws.png" },
    { "name": "SM", "alias": "San Marino", "mini": "http://flags.fmcdn.net/data/flags/mini/sm.png", "normal": "http://flags.fmcdn.net/data/flags/big/sm.png" },
    { "name": "STP", "alias": "Sao Tome and Principe", "mini": "http://flags.fmcdn.net/data/flags/mini/st.png", "normal": "http://flags.fmcdn.net/data/flags/big/st.png" },
    { "name": "Arab", "alias": "Saudi Arabia", "mini": "http://flags.fmcdn.net/data/flags/mini/sa.png", "normal": "http://flags.fmcdn.net/data/flags/big/sa.png" },
    { "name": "Senegal", "mini": "http://flags.fmcdn.net/data/flags/mini/sn.png", "normal": "http://flags.fmcdn.net/data/flags/big/sn.png" },
    { "name": "Serbia", "mini": "http://flags.fmcdn.net/data/flags/mini/rs.png", "normal": "http://flags.fmcdn.net/data/flags/big/rs.png" },
    { "name": "Seychelles", "mini": "http://flags.fmcdn.net/data/flags/mini/sc.png", "normal": "http://flags.fmcdn.net/data/flags/big/sc.png" },
    { "name": "Sierra", "alias": "Sierra Leone", "mini": "http://flags.fmcdn.net/data/flags/mini/sl.png", "normal": "http://flags.fmcdn.net/data/flags/big/sl.png" },
    { "name": "Singapore", "mini": "http://flags.fmcdn.net/data/flags/mini/sg.png", "normal": "http://flags.fmcdn.net/data/flags/big/sg.png" },
    { "name": "Slovakia", "mini": "http://flags.fmcdn.net/data/flags/mini/sk.png", "normal": "http://flags.fmcdn.net/data/flags/big/sk.png" },
    { "name": "Slovenia", "mini": "http://flags.fmcdn.net/data/flags/mini/si.png", "normal": "http://flags.fmcdn.net/data/flags/big/si.png" },
    { "name": "Solomon", "alias": "Solomon Islands", "mini": "http://flags.fmcdn.net/data/flags/mini/sb.png", "normal": "http://flags.fmcdn.net/data/flags/big/sb.png" },
    { "name": "Somalia", "mini": "http://flags.fmcdn.net/data/flags/mini/so.png", "normal": "http://flags.fmcdn.net/data/flags/big/so.png" },
    { "name": "RSA", "alias": "Republic of South Africa", "mini": "http://flags.fmcdn.net/data/flags/mini/za.png", "normal": "http://flags.fmcdn.net/data/flags/big/za.png" },
    { "name": "SKorea", "alias": "South Korea", "mini": "http://flags.fmcdn.net/data/flags/mini/kr.png", "normal": "http://flags.fmcdn.net/data/flags/big/kr.png" },
    { "name": "SSudan", "alias": "South Sudan", "mini": "http://flags.fmcdn.net/data/flags/mini/ss.png", "normal": "http://flags.fmcdn.net/data/flags/big/ss.png" },
    { "name": "Spain", "mini": "http://flags.fmcdn.net/data/flags/mini/es.png", "normal": "http://flags.fmcdn.net/data/flags/big/es.png" },
    { "name": "Lanka", "alias": "Shri Lanka", "mini": "http://flags.fmcdn.net/data/flags/mini/lk.png", "normal": "http://flags.fmcdn.net/data/flags/big/lk.png" },
    { "name": "Sudan", "mini": "http://flags.fmcdn.net/data/flags/mini/sd.png", "normal": "http://flags.fmcdn.net/data/flags/big/sd.png" },
    { "name": "Suriname", "mini": "http://flags.fmcdn.net/data/flags/mini/sr.png", "normal": "http://flags.fmcdn.net/data/flags/big/sr.png" },
    { "name": "Swaziland", "mini": "http://flags.fmcdn.net/data/flags/mini/sz.png", "normal": "http://flags.fmcdn.net/data/flags/big/sz.png" },
    { "name": "Sweden", "mini": "http://flags.fmcdn.net/data/flags/mini/se.png", "normal": "http://flags.fmcdn.net/data/flags/big/se.png" },
    { "name": "Switzerland", "mini": "http://flags.fmcdn.net/data/flags/mini/ch.png", "normal": "http://flags.fmcdn.net/data/flags/big/ch.png" },
    { "name": "Syria", "mini": "http://flags.fmcdn.net/data/flags/mini/sy.png", "normal": "http://flags.fmcdn.net/data/flags/big/sy.png" },
    { "name": "Tajikistan", "mini": "http://flags.fmcdn.net/data/flags/mini/tj.png", "normal": "http://flags.fmcdn.net/data/flags/big/tj.png" },
    { "name": "Tanzania", "mini": "http://flags.fmcdn.net/data/flags/mini/tz.png", "normal": "http://flags.fmcdn.net/data/flags/big/tz.png" },
    { "name": "Thailand", "mini": "http://flags.fmcdn.net/data/flags/mini/th.png", "normal": "http://flags.fmcdn.net/data/flags/big/th.png" },
    { "name": "Togo", "mini": "http://flags.fmcdn.net/data/flags/mini/tg.png", "normal": "http://flags.fmcdn.net/data/flags/big/tg.png" },
    { "name": "Tonga", "mini": "http://flags.fmcdn.net/data/flags/mini/to.png", "normal": "http://flags.fmcdn.net/data/flags/big/to.png" },
    { "name": "Trinidad", "alias": "Trinidad and Tobago", "mini": "http://flags.fmcdn.net/data/flags/mini/tt.png", "normal": "http://flags.fmcdn.net/data/flags/big/tt.png" },
    { "name": "Tunisia", "mini": "http://flags.fmcdn.net/data/flags/mini/tn.png", "normal": "http://flags.fmcdn.net/data/flags/big/tn.png" },
    { "name": "Turkey", "alias": "Türkiye", "mini": "http://flags.fmcdn.net/data/flags/mini/tr.png", "normal": "http://flags.fmcdn.net/data/flags/big/tr.png" },
    { "name": "Turkmenistan", "mini": "http://flags.fmcdn.net/data/flags/mini/tm.png", "normal": "http://flags.fmcdn.net/data/flags/big/tm.png" },
    { "name": "Tuvalu", "mini": "http://flags.fmcdn.net/data/flags/mini/tv.png", "normal": "http://flags.fmcdn.net/data/flags/big/tv.png" },
    { "name": "Uganda", "mini": "http://flags.fmcdn.net/data/flags/mini/ug.png", "normal": "http://flags.fmcdn.net/data/flags/big/ug.png" },
    { "name": "Ukraine", "mini": "http://flags.fmcdn.net/data/flags/mini/ua.png", "normal": "http://flags.fmcdn.net/data/flags/big/ua.png" },
    { "name": "UAE", "alias": "United Arab Emirates", "mini": "http://flags.fmcdn.net/data/flags/mini/ae.png", "normal": "http://flags.fmcdn.net/data/flags/big/ae.png" },
    { "name": "UK", "alias": "United Kingdom", "mini": "http://flags.fmcdn.net/data/flags/mini/gb.png", "normal": "http://flags.fmcdn.net/data/flags/big/gb.png" },
    { "name": "USA", "alias": "United States of America", "mini": "http://flags.fmcdn.net/data/flags/mini/us.png", "normal": "http://flags.fmcdn.net/data/flags/big/us.png" },
    { "name": "Uruguay", "mini": "http://flags.fmcdn.net/data/flags/mini/uy.png", "normal": "http://flags.fmcdn.net/data/flags/big/uy.png" },
    { "name": "Uzbekistan", "mini": "http://flags.fmcdn.net/data/flags/mini/uz.png", "normal": "http://flags.fmcdn.net/data/flags/big/uz.png" },
    { "name": "Vanuatu", "mini": "http://flags.fmcdn.net/data/flags/mini/vu.png", "normal": "http://flags.fmcdn.net/data/flags/big/vu.png" },
    { "name": "Vatican", "alias": "Vatican City", "mini": "http://flags.fmcdn.net/data/flags/mini/va.png", "normal": "http://flags.fmcdn.net/data/flags/big/va.png" },
    { "name": "Venezuela", "mini": "http://flags.fmcdn.net/data/flags/mini/ve.png", "normal": "http://flags.fmcdn.net/data/flags/big/ve.png" },
    { "name": "Vietnam", "mini": "http://flags.fmcdn.net/data/flags/mini/vn.png", "normal": "http://flags.fmcdn.net/data/flags/big/vn.png" },
    { "name": "Sahara", "alias": "Western Sahara", "mini": "http://flags.fmcdn.net/data/flags/mini/eh.png", "normal": "http://flags.fmcdn.net/data/flags/big/eh.png" },
    { "name": "Wales", "mini": "http://flags.fmcdn.net/data/flags/mini/gb-wls.png", "normal": "http://flags.fmcdn.net/data/flags/big/gb-wls.png" },
    { "name": "Yemen", "mini": "http://flags.fmcdn.net/data/flags/mini/ye.png", "normal": "http://flags.fmcdn.net/data/flags/big/ye.png" },
    { "name": "Zambia", "mini": "http://flags.fmcdn.net/data/flags/mini/zm.png", "normal": "http://flags.fmcdn.net/data/flags/big/zm.png" },
    { "name": "Zimbabwe", "mini": "http://flags.fmcdn.net/data/flags/mini/zw.png", "normal": "http://flags.fmcdn.net/data/flags/big/zw.png" }];

